pipeline {
    agent any
    environment {
        ANSIBLE_INVENTORY = 'hosts'
        ANSIBLE_PLAYBOOK = 'install_nginx.yml'
        SSH_CREDENTIALS_ID = 'pemkey'
    }
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/cfvghjkl/ansible.git'
            }
        }
       
        stage('Run Ansible Playbook') {
            steps {
                withCredentials([sshUserPrivateKey(credentialsId: SSH_CREDENTIALS_ID, keyFileVariable: 'SSH_KEY')]) {
                    sh '''
                    ansible-playbook -i ${ANSIBLE_INVENTORY} ${ANSIBLE_PLAYBOOK} --private-key $SSH_KEY
                '''
            }
          }     
        }
    }
}
