name : Run Ansible Playbook
on: 
  push:
    branches: [main]

jobs:
  ansible:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v3
          
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.9'

        - name: Install Ansible
          run: pip install ansible
          
        - name: Run Ansible Playbook
          run: ansible-playbook install_nginx.yml |tee ansible.log

        - name: Upload Ansible Log
          uses: actions/upload-artifacts@v3
          with:
            name: ansible-log
            path: ansible.log
        - name: Read
          run: cat ansible.log    