name : my first workflow
on : push 
jobs:
    my_firt_job:
        runs-on: ubuntu-latest
        steps:
           - name: welcome
             run : echo "welcome"

           - name: checkout Repo
             run : actions/checkout@v4
             
           - name : files
             run : ls
